### ISSUE TITLE
TODO / Want Help List 1R

### ISSUE THREAD

**Issue by 0999312** [0999312/Umapyoi-Models#1]
顺序按照优先级进行划分，需要重做 / 等待部件的角色优先进行处理。  
需要重做/需要加工的角色：Need Modification  
- [x] 美浦波旁 Mihono Bourbon ：润色中
***  
已确定正在制作中：WIP
- [x] 葛城王牌  Katsuragi Ace
- [x] 好歌剧 / 歌剧王 TM Opera O —— 千代
- [x] 爱慕织姬 Admire Vega —— 大宝
- [x] 大和赤骥  Daiwa Scarlet
- [x] 美妙姿势 Fine Motion —— 美妙姿势（bb61iowa）
- [ ] 目白多伯 Mejiro Dober —— 大宝
- [x] 丸善斯基 Maruzensky  —— KusozakoAtama10k
- [ ] 胜利奖券  Winning Ticket —— Crystal Kingdom
- [x] 成田大进  Narita Taishin —— Dumnheint 
- [ ] 好歌剧（新年） TM Opera O【初晴・青き絢爛】—— 西宫
- [ ] 青竹回忆 Bamboo Memory —— 西宫
- [ ] 优秀素质（新年） Nice Nature【ネガイノカサネ】 —— 西宫
- [ ] 八重无敌 Yaeno Muteki —— 西宫
- [ ] 鹤丸刚志 Tsurumaru Tsuyoshi —— 西宫
- [ ] 北方飞翔 North Flight —— 美妙姿势（bb61iowa）
- [x] 烈焰快驹 Dantsu Flame —— SUZUNA
***  
未动工人物：Unstarted:   
- [x] 醒目飞鹰  Smart Falcon —— Dumnheint
- [ ] 天狼星象征  Sirius Symboli   
- [ ] 西野花 Nishino Flower  
- [x] 北港火山 Hokko Tarumae  
- [ ] 奇锐骏 Wonder Acute
- [ ] 生野狄杜斯  Ikuno Dictus  
- [x] 神鹰  El Condor Pasa  
- [x] 圣王光辉  King Halo  
- [ ] 气槽  Air Groove  
- [x] 富士奇迹  Fuji Kiseki  
- [ ] 成田白仁  Narita Brian
- [ ] 琵琶晨光  Biwa Hayahide

**Comment by 0999312** [comment]
需要加工的角色详细：
- [ ] 草上飞 鞋子细节修改
- [ ] 真弓快车 红黄肩带以及腰间装饰

**Comment by 0999312** [comment]
已确定没有人员接手的半成品： WIP Model (No one on duty):

- [x] 爱丽数码 Agnes Digital —— Only Head
- [ ] 目白高峰 Mejiro Ramonu
